<?php

namespace Megaads\DealsPage\Repositories;

use Megaads\DealsPage\Models\Catalog;

class CatalogRepository extends BaseRepository
{
    public function create($item)
    {

    }

    /**
     * @param $items
     * @return bool
     */
    public function bulkCreate($items = []) {
        $reVal = false;
        try {
            Catalog::insert($items);
            $reVal = true;
        } catch (\Exception $ex) {
            dealPageSysLog('error', 'BULK_CREATE_CATALOG: ', $ex);
        }
        return $reVal;
    }

    public function read($filters)
    {
        parent::read(); // TODO: Change the autogenerated stub
    }

    public function update($id, $params)
    {
        parent::update(); // TODO: Change the autogenerated stub
    }

    public function delete($id)
    {
        parent::delete(); // TODO: Change the autogenerated stub
    }

}